#!/usr/bin/env python3
"""Independent finite-dimensional LP check for the k=2.5 and k=1.5 optimizers.

Requires NumPy and SciPy (HiGHS).  The analytic curves are imported from
``generate_data.py``; the linear program itself uses only the marginal,
martingale, and support constraints and does not use those curves.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from scipy.optimize import linprog
from scipy.sparse import coo_matrix

from generate_data import LargeRegime, SmallRegime, expectation, tex_scientific

ROOT = Path(__file__).resolve().parents[1]
FIGURES = ROOT / "figures"
CASES = ((2.5, LargeRegime, "KTwoFive", "k25"), (1.5, SmallRegime, "KOneFive", "k15"))


def solve_grid(size: int, k: float, coupling: LargeRegime | SmallRegime) -> dict[str, object]:
    source = -1.0 + (np.arange(size) + 0.5) * (2.0 / size)
    target = -2.0 + (np.arange(2 * size) + 0.5) * (2.0 / size)

    source_index: list[int] = []
    target_index: list[int] = []
    costs: list[float] = []
    for i, x in enumerate(source):
        for j, y in enumerate(target):
            if y >= x - k - 1.0e-12:
                source_index.append(i)
                target_index.append(j)
                costs.append((y - x) ** 3)

    source_index_array = np.asarray(source_index, dtype=int)
    target_index_array = np.asarray(target_index, dtype=int)
    variable_count = len(costs)
    columns = np.arange(variable_count, dtype=int)

    row_indices = np.concatenate(
        (
            source_index_array,
            size + target_index_array,
            3 * size + source_index_array,
        )
    )
    column_indices = np.concatenate((columns, columns, columns))
    martingale_coefficients = (
        target[target_index_array] - source[source_index_array]
    )
    coefficients = np.concatenate(
        (np.ones(variable_count), np.ones(variable_count), martingale_coefficients)
    )
    matrix = coo_matrix(
        (coefficients, (row_indices, column_indices)),
        shape=(4 * size, variable_count),
    ).tocsr()
    right_hand_side = np.concatenate(
        (
            np.full(size, 1.0 / size),
            np.full(2 * size, 1.0 / (2.0 * size)),
            np.zeros(size),
        )
    )

    # The last target equation is redundant with the source equations.
    keep = np.ones(4 * size, dtype=bool)
    keep[3 * size - 1] = False
    result = linprog(
        np.asarray(costs),
        A_eq=matrix[keep],
        b_eq=right_hand_side[keep],
        bounds=(0.0, None),
        method="highs",
        options={
            "dual_feasibility_tolerance": 1.0e-9,
            "primal_feasibility_tolerance": 1.0e-9,
        },
    )
    if not result.success:
        raise RuntimeError(f"HiGHS failed for N={size}: {result.message}")

    plan = np.asarray(result.x)
    row_masses = np.bincount(source_index_array, weights=plan, minlength=size)
    column_masses = np.bincount(target_index_array, weights=plan, minlength=2 * size)
    martingale = np.bincount(
        source_index_array,
        weights=plan * martingale_coefficients,
        minlength=size,
    )
    graph_distance = 0.0
    for variable, mass in enumerate(plan):
        if mass <= 0.0:
            continue
        i = source_index[variable]
        j = target_index[variable]
        lower, upper, _ = coupling.maps(float(source[i]))
        graph_distance += mass * min(
            abs(float(target[j]) - lower), abs(float(target[j]) - upper)
        )

    return {
        "size": size,
        "source": source,
        "target": target,
        "source_index": source_index_array,
        "target_index": target_index_array,
        "plan": plan,
        "value": float(result.fun),
        "distance": graph_distance,
        "row_residual": float(np.max(np.abs(row_masses - 1.0 / size))),
        "column_residual": float(
            np.max(np.abs(column_masses - 1.0 / (2.0 * size)))
        ),
        "martingale_residual": float(np.max(np.abs(martingale))),
    }


def main() -> None:
    FIGURES.mkdir(exist_ok=True)
    tex_lines = ["% Generated by numerics/discrete_lp.py; do not edit by hand."]
    for k, regime, macro, tag in CASES:
        coupling = regime(k)
        reference = expectation(coupling, lambda displacement: displacement**3)
        results = [solve_grid(size, k, coupling) for size in (20, 40, 80, 120)]
        for result in results:
            if max(
                float(result["row_residual"]),
                float(result["column_residual"]),
                float(result["martingale_residual"]),
            ) > 1.0e-10:
                raise AssertionError(f"LP equality residual too large for k={k}, N={result['size']}")
        errors = [float(result["value"]) - reference for result in results]
        if not all(earlier > later > 0.0 for earlier, later in zip(errors, errors[1:])):
            raise AssertionError(f"the displayed LP objective errors are not decreasing for k={k}")

        with (FIGURES / f"lp_convergence_{tag}.dat").open("w", encoding="ascii") as stream:
            stream.write("N value error distance row_residual column_residual martingale_residual\n")
            for result in results:
                stream.write(
                    f"{result['size']} {result['value']:.14f} "
                    f"{float(result['value'])-reference:.14e} {result['distance']:.14e} "
                    f"{result['row_residual']:.4e} {result['column_residual']:.4e} "
                    f"{result['martingale_residual']:.4e}\n"
                )

        result_80 = next(result for result in results if result["size"] == 80)
        with (FIGURES / f"lp_support_{tag}.dat").open("w", encoding="ascii") as stream:
            stream.write("x y mass relative_mass\n")
            for variable, mass in enumerate(result_80["plan"]):
                if mass <= 1.0e-10:
                    continue
                i = int(result_80["source_index"][variable])
                j = int(result_80["target_index"][variable])
                stream.write(
                    f"{float(result_80['source'][i]):.12f} "
                    f"{float(result_80['target'][j]):.12f} {float(mass):.12e} "
                    f"{float(mass)*160.0:.12e}\n"
                )

        rows = []
        for result in results:
            rows.append(
                f"{result['size']} & {result['value']:.10f} & "
                f"${tex_scientific(float(result['value'])-reference)}$ & "
                f"${tex_scientific(float(result['distance']))}$ \\\\"
            )
        suffix = "" if macro == "KTwoFive" else macro
        tex_lines.extend(
            (
                f"\\newcommand{{\\CubicReference{macro}}}{{{reference:.12f}}}",
                f"\\newcommand{{\\LPConvergenceRows{suffix}}}{{%",
                *rows,
                "}",
            )
        )
        for result in results:
            print(
                f"k={k}, N={result['size']:3d}: value={result['value']:.12f}, "
                f"error={float(result['value'])-reference:.3e}, "
                f"distance={result['distance']:.3e}"
            )
    tex_lines.append("")
    (ROOT / "numerics" / "generated_lp_values.tex").write_text("\n".join(tex_lines), encoding="ascii")


if __name__ == "__main__":
    main()
