#!/usr/bin/env python3
"""Regenerate the manuscript's cost/binding-mass comparison table.

Uses the existing coupling formulas and standard-library Simpson quadrature.
The 2,400- and 4,800-panel calculations must agree at the four displayed
decimal places. This is a numerical stability check, not an error bound or
an ingredient of the optimality proof.
"""

from __future__ import annotations

import math
from pathlib import Path

from generate_data import LargeRegime, SmallRegime, expectation, integrate_by_branch, simpson


PARAMETERS = (1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0)
PANELS = (2400, 4800)
OUTPUT = Path(__file__).resolve().with_name("comparison_table_rows.tex")
Coupling = LargeRegime | SmallRegime


def cubic_value(coupling: Coupling, panels: int) -> float:
    if panels == 2400:
        return expectation(coupling, lambda displacement: displacement**3)

    def integrand(x: float) -> float:
        lower, upper, probability_upper = coupling.maps(x)
        return 0.5 * (
            (1.0 - probability_upper) * (lower - x) ** 3
            + probability_upper * (upper - x) ** 3
        )

    return integrate_by_branch(coupling, integrand, panels_per_branch=panels)


def binding_mass(coupling: Coupling, panels: int) -> float:
    # The binding lower branch is D(x)=x-k for b <= x <= 1.
    # The active interval is empty at k=3.
    if coupling.k == 3.0:
        return 0.0

    def integrand(x: float) -> float:
        _, _, probability_upper = coupling.maps(x)
        return 0.5 * (1.0 - probability_upper)

    return simpson(integrand, coupling.b, 1.0, panels)


def main() -> None:
    rows = [
        "% Generated by numerics/generate_comparison_table.py; do not edit by hand.",
        "% Simpson quadrature at 2400 and 4800 panels agrees at four decimals.",
        r"\newcommand{\ComparisonRows}{%",
    ]
    largest_change = 0.0
    for k in PARAMETERS:
        coupling = SmallRegime(k) if k < 2.0 else LargeRegime(k)
        values = [
            (cubic_value(coupling, panels), binding_mass(coupling, panels))
            for panels in PANELS
        ]
        coarse, fine = values
        if not all(math.isfinite(value) for pair in values for value in pair):
            raise ArithmeticError(f"nonfinite quadrature result for k={k}")
        for name, first, second in zip(("cubic cost", "binding mass"), coarse, fine):
            if f"{first:.4f}" != f"{second:.4f}":
                raise ArithmeticError(
                    f"four-decimal stability check failed for {name} at k={k}: "
                    f"{first:.12f} versus {second:.12f}"
                )
            largest_change = max(largest_change, abs(second - first))
        value, mass = fine
        if not 0.0 <= mass <= 0.5 * (3.0 - k):
            raise ArithmeticError(f"binding mass exceeds the active source mass at k={k}")
        rows.append(f"{k:.2f} & {value:.4f} & {mass:.4f}" + r" \\")
        print(
            f"k={k:.2f}: V={value:.12f}, binding mass={mass:.12f}; "
            f"refinement changes=({abs(fine[0]-coarse[0]):.3e}, "
            f"{abs(fine[1]-coarse[1]):.3e})"
        )
    rows.append("}")
    OUTPUT.write_text("\n".join(rows) + "\n", encoding="ascii")
    print(f"Wrote {OUTPUT}; largest refinement change={largest_change:.3e}")


if __name__ == "__main__":
    main()
