#!/usr/bin/env python3
"""Generate the actual curves in the construction/proof illustrations.

Run from any directory with Python's standard library. Schematic target
intervals and gap profiles are drawn directly in the corresponding TeX files;
they are explicitly identified as schematics in their captions.
"""

from pathlib import Path

from generate_data import SmallRegime, bisect_root, evenly_spaced


ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    (ROOT / "figures").mkdir(exist_ok=True)
    coupling = SmallRegime(1.5)
    lower_x, upper_x = 0.0, 0.85
    lower_alpha = bisect_root(
        lambda s: coupling.maps(s)[0] - (lower_x - coupling.k), -1, coupling.b
    )
    upper_alpha = bisect_root(
        lambda s: coupling.maps(s)[1] - (upper_x - coupling.k), -1, coupling.x_0
    )
    points = set(evenly_spaced(-1, 1, 501))
    points.update(evenly_spaced(-1, coupling.x_0, 101))
    points.update((coupling.x_0, coupling.b, lower_alpha, upper_alpha))
    with (ROOT / "figures/predecessor_support.dat").open("w") as stream:
        stream.write("s D U B\n")
        for source in sorted(points):
            lower, upper, _ = coupling.maps(source)
            stream.write(f"{source:.12f} {lower:.12f} {upper:.12f} {source-coupling.k:.12f}\n")

    small = SmallRegime(1.1)
    lower, upper, _ = small.maps(small.x_0)
    v0, w0 = small.x_0 - lower, upper - small.x_0
    tau = (v0 + w0) / 2
    t_end = bisect_root(lambda s: s - small.maps(s)[0] - tau, small.x_0, small.b)
    alpha_star = bisect_root(lambda s: small.maps(s)[1] - s - tau, -1, small.x_0)
    lambda_end = (t_end - small.x_0) / (small.b - small.x_0)
    with (ROOT / "figures/middle_displacements.dat").open("w") as stream:
        stream.write("lambda v w\n")
        for fraction in evenly_spaced(0, 1, 201):
            source = small.x_0 + fraction * (small.b - small.x_0)
            lower, upper, _ = small.maps(source)
            stream.write(f"{fraction:.12f} {source-lower:.12f} {upper-source:.12f}\n")

    values = {
        "TraceLowerX": lower_x,
        "TraceLowerAlpha": lower_alpha,
        "TraceLowerY": lower_x-coupling.k,
        "TraceUpperX": upper_x,
        "TraceUpperAlpha": upper_alpha,
        "TraceUpperY": upper_x-coupling.k,
        "ComparisonTau": tau,
        "ComparisonEnd": lambda_end,
        "ComparisonXZero": small.x_0,
        "ComparisonTEnd": t_end,
        "ComparisonYEnd": small.maps(t_end)[1],
        "ComparisonXStar": alpha_star+small.k+tau,
    }
    with (ROOT / "numerics/generated_explanatory_values.tex").open("w") as stream:
        stream.write("% Generated by numerics/generate_explanatory_figures.py.\n")
        for name, value in values.items():
            stream.write(f"\\newcommand{{\\{name}}}{{{value:.10f}}}\n")
    if not (lower_alpha < coupling.b < lower_x < coupling.k-1 < upper_x):
        raise ArithmeticError("The lower predecessor is in the wrong regime.")
    if not (-1 < upper_alpha < coupling.x_0 and v0 < tau < w0 and 0 < lambda_end < 1):
        raise ArithmeticError("The illustrated proof geometry is invalid.")
    print("Generated predecessor and middle-displacement curves from the exact parametrizations.")
    print(f"Exceptional source interval: ({small.x_0:.8f}, {t_end:.8f}).")
    print(f"Its target image: (-0.1, {small.maps(t_end)[1]:.8f}); x_*={values['ComparisonXStar']:.8f}.")


if __name__ == "__main__":
    main()
